### ISSUE TITLE
nodejs with error to exit

### ISSUE THREAD

**Issue by kn007** [Arch1tect/Chatbox#12]
```
Missing error handler on `socket`.
TypeError: Cannot read property 'length' of undefined
    at Socket.<anonymous> (/data/www/Chatbox/index.js:176:47)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/data/www/Chatbox/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/data/www/Chatbox/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/data/www/Chatbox/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/data/www/Chatbox/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/data/www/Chatbox/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/data/www/Chatbox/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:77:13)
test closed a connection.
/data/www/Chatbox/index.js:148
        var socketIndexInUser = user.socketList.indexOf(socket);
                                               ^

TypeError: Cannot read property 'indexOf' of undefined
    at Socket.<anonymous> (/data/www/Chatbox/index.js:148:48)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.emit (/data/www/Chatbox/node_modules/socket.io/lib/socket.js:128:10)
    at Socket.onclose (/data/www/Chatbox/node_modules/socket.io/lib/socket.js:425:8)
    at Client.onclose (/data/www/Chatbox/node_modules/socket.io/lib/client.js:232:24)
    at Client.onerror (/data/www/Chatbox/node_modules/socket.io/lib/client.js:213:8)
    at Client.ondata (/data/www/Chatbox/node_modules/socket.io/lib/client.js:177:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

using pm2 could not see this error.

still find the problem

**Comment by kn007** [comment]
Fix this issue in https://github.com/kn007/Chatbox/commit/5228bc60e748beb92c607d2a94cda9c1f53d3cc2
